python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.9 --jump_prob 1.0
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.8 --jump_prob 1.0
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.7 --jump_prob 1.0
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.6 --jump_prob 1.0
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.5 --jump_prob 1.0
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.1
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.2
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.3
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.4
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.5
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.6
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.7
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.8
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 0.9
python Glosten_Milgrom_ModelFree.py --informed 0.4 --jump_prob 1.0